# Generated by Django 4.2.10 on 2024-04-10 16:16

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=account.models.get_file_path
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=64)),
                (
                    "first_name_fa",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "last_name_fa",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("username", models.CharField(max_length=16, unique=True)),
                (
                    "national_code",
                    models.CharField(
                        blank=True, default="", max_length=10, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=11)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=256)),
                ("home", models.CharField(blank=True, default="", max_length=8)),
                ("manager", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
