# Generated by Django 4.2.10 on 2024-06-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
