# Generated by Django 4.2.10 on 2024-07-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='date_registered',
        ),
    ]
