# Generated by Django 4.2.10 on 2024-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_date_joined_user_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_registered',
            field=models.DateField(),
        ),
    ]
