# Generated by Django 4.2.10 on 2024-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_registered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
