# Generated by Django 4.2.10 on 2024-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_date_history_date_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_changed',
            field=models.DateField(),
        ),
    ]
