# Generated by Django 4.2.10 on 2024-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_history_date_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
