# Generated by Django 4.2.10 on 2024-06-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_subscription_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='price',
            new_name='amount',
        ),
    ]
