# Generated by Django 4.2.10 on 2024-06-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_rename_price_subscription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
