# Generated by Django 4.2.10 on 2024-07-07 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0010_alter_subscription_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='year',
            new_name='section_year',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('section_year', 'user')},
        ),
    ]
