# Generated by Django 4.2.10 on 2024-07-26 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_rename_year_subscription_section_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
